abort configure if libiconv.h cannot be found

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -26,7 +26,14 @@ AC_PROG_INSTALL
 
 dnl ======================== Default setting
 ALL_LINGUAS="cs de et fi nl sk pl it sl"
+AC_CHECK_HEADERS(libintl.h)
 AM_GNU_GETTEXT
+if test x$USE_NLS = xyes -a x$ac_cv_header_libintl_h != xyes; then
+	echo '*************************************************'
+	echo 'libintl.h is missing, use --disable-nls'
+	echo '*************************************************'
+	exit 1
+fi
 
 dnl ======================== Check for include/config.h.in
 AC_MSG_CHECKING([for include/config.h.in])
