Deprecate gnokii-debug target

diff --git a/testsuite/testit b/testsuite/testit
--- a/testsuite/testit
+++ b/testsuite/testit
@@ -1,12 +1,11 @@
 #!/bin/bash
 (
 	cd ..
-	make
-	cd common
-	make gnokii-debug || ( echo "*** Compile FAILED"; sleep 10 )
+	./configure --disable-shared
+	make || ( echo "*** Compile FAILED"; sleep 10 )
 )
 export HOME=`pwd`
-GNOKII=../common/gnokii-debug
+GNOKII=../gnokii/gnokii
 for A in test.0.identify test.1.sms test.10.oplogo test.11.ringtone test.13.emspicture test.14.oplogo-xpm test.16.imelody test.17.picture2 test.18.emsanimation test.2.concatsms; do
     echo -n "Doing $A... "
     B=`echo $A | sed s/test/out/`
